### PR TITLE
WIP - DON'T MERGE: Lagom Scala multi service integration test

### PR DESCRIPTION
**Pull request by markusjura**
Lagom Scala multi service integration test

Adding multi service integration tests for Lagom Scala. Also, upgrading Lagom to 1.3.1

### CODE REVIEW

**Comment by markusjura** [comment]
CI is failing because in Lagom 1.3.1 the new integration test is failing. Once, a new Lagom version is released, we can update it here and the tests should pass.

**Comment by markusjura** [comment]
The integration test is passing but the produced bundle cannot be loaded onto ConductR:

```
conduct load /Users/mj/workspace/sbt-conductr/sbt-conductr-tester/lagom-java-bundle/lagom-service-impl/target/bundle/lagom-service-impl-v0-42eb32075b87b72dd1e8571a6453ab9d2339674927f5bd381b1bf7b5afa0e7c1.zip
Retrieving bundle..
Retrieving file:///Users/mj/workspace/sbt-conductr/sbt-conductr-tester/lagom-java-bundle/lagom-service-impl/target/bundle/lagom-service-impl-v0-42eb32075b87b72dd1e8571a6453ab9d2339674927f5bd381b1bf7b5afa0e7c1.zip
Loading bundle to ConductR..
Error: Unable to contact ConductR.
Error: Reason: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
Error: Start the ConductR sandbox with: sandbox run IMAGE_VERSION
```

So it seems that the produced `bundle.conf` is invalid which would meant that our prior java test and the new scala test is also invalid:

```
endpoints = {
  "paymentservice" = {
    bind-protocol = "http"
    bind-port     = 0
    service-name  = "paymentservice"
    acls          = [
      {
        http = {
          requests = [
            {
              path-beg = "/credit"
            }
          ]
        }
      },
      {
        http = {
          requests = [
            {
              path-beg = "/debit"
            }
          ]
        }
      }
    ]
  },
  "akka-remote" = {
    bind-protocol = "tcp"
    bind-port = 0
    services= []
  }
}
```

**Comment by markusjura** [comment]
This PR can only be merged if the issue https://github.com/lagom/lagom/issues/580#issuecomment-284734076 has been resolved.

Afterward, the tests of this PR are adjusted accordingly.

**Comment by ignasi35** [comment]
This is superseded by #243, #226 , #224 and #234

**Pull request closed without merging**
