### PR TITLE
Update sbt-native-packager to version 1.3.2

### PR DESCRIPTION
**Pull request by TimMoore**
This includes improved Docker support.

### CODE REVIEW

**Comment by typesafe-tools** [comment]
Build triggered. sha1 is merged.

**Comment by typesafe-tools** [comment]
Build started sha1 is merged.

**Comment by typesafe-tools** [comment]
Build finished.

**Comment by TimMoore** [comment]
See also https://github.com/lightbend/sbt-reactive-app/pull/12

**Comment by TimMoore** [comment]
@typesafehub/enterprise-suite-platform can this be merged?

**Comment by longshorej** [comment]
I’ll check it out tomorrow, need to think through implications a bit.

**Comment by longshorej** [comment]
Thanks @TimMoore  - this checked out, still able to produce OCI and Universal bundles correctly. Seems to yield 50 to 100MB savings for most of the Chirper services.

**Pull request merged**
