### PR TITLE
Increase default resident memory to 384MB

### PR DESCRIPTION
**Pull request by fsat**
- Update default for both Play and Lagom project
- Update README.md

### CODE REVIEW

**Comment by fsat** [comment]
This is related to https://github.com/typesafehub/conductr/issues/1360 and https://github.com/typesafehub/conductr/pull/1364.

When deploying to Mesos, it is observed that 256MB resident memory for both ConductR Agent and the bundle is not sufficient. Once increased to 384MB, the ConductR Agent and the bundles are both running just fine. At the time of writing, it's 2 hours since the soak test began.

Marked as wip for now until longer soak test is completed.

**Comment by huntc** [comment]
How about the readme? Perhaps do a search for 256? I'd expect some scripted tests to also pick this up...

**Comment by fsat** [comment]
I've got some problem running scripted test on my machine, it seems to stop progressing and doesn't fail after going through a number of tests - so making this PR so I can try it on travis.

Thanks for the reminder for the readme, I'll be sure to update it.

**Comment by fsat** [comment]
Travis build hung at `/etc/default/docker`:

```
Configuration file '/etc/default/docker'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** docker (Y/I/N/O/D/Z) [default=N] ?
```

**Comment by fsat** [comment]
I've sort out the build on my machine by restarting the docker VM. All build has passed on my local machine, now just need to figure out what to do with travis.

**Comment by fsat** [comment]
Using `-o Dpkg::Options::="--force-confold"` flag when installing Docker to use existing Docker configuration on `/etc/default/docker`.

Based on the following article:
https://raphaelhertzog.com/2010/09/21/debian-conffile-configuration-file-managed-by-dpkg/

**Comment by fsat** [comment]
Travis build is now progressing with the additional option to keep the existing config when installing docker.

**Comment by markusjura** [comment]
LGTM

**Comment by fsat** [comment]
Latest change is to reorder commits, also amend with fixes for the broken tests.

**Comment by huntc** [comment]
Lgtm

**Pull request merged**
