### PR TITLE
Support feature arg args in sandbox run parser

### PR DESCRIPTION
**Pull request by pvlugter**
Update feature args to have optional extra args: `--feature NAME [ ARGS ... ]` to align with: https://github.com/typesafehub/conductr-cli/pull/170

### CODE REVIEW

**Comment by pvlugter** [comment]
Looks like the same build failure is also [on master](https://travis-ci.org/typesafehub/sbt-conductr/builds/167560590) and due to 9999 having been removed from ConductR ports here: https://github.com/typesafehub/conductr-cli/commit/a9ac2b1

I can update the tests.

**Comment by markusjura** [comment]
@pvlugter Tested this PR with the `sbt-conductr/sbt-conductr-tester/bundle` sbt test project. The parser fails when specifying additional arguments to the monitoring feature:

```
> sandbox run 1.1.9 --feature monitoring v2
usage: sandbox [-h] {run,debug,stop,init} ...
sandbox: error: unrecognized arguments: v2
[success] Total time: 1 s, completed Oct 23, 2016 11:46:39 AM
> sandbox run 1.1.9 --feature monitoring 2.1.0-RC2
usage: sandbox [-h] {run,debug,stop,init} ...
sandbox: error: unrecognized arguments: 2.1.0-RC2
[success] Total time: 1 s, completed Oct 23, 2016 11:46:48 AM
> sandbox run 1.1.9 --feature monitoring snapshot 2.1.0-20161018-43bab24
usage: sandbox [-h] {run,debug,stop,init} ...
sandbox: error: unrecognized arguments: snapshot 2.1.0-20161018-43bab24
[success] Total time: 1 s, completed Oct 23, 2016 11:46:58 AM
```

**Comment by markusjura** [comment]
PR https://github.com/typesafehub/sbt-conductr/pull/174 fixes the parsing issue.

**Comment by pvlugter** [comment]
@markusjura: those commands work fine for me in the tester project. Are you sure you ran it with the new CLI? The `unrecognized arguments` suggests that it's an older CLI without the new nargs for features.

**Comment by markusjura** [comment]
@pvlugter I've retested it and you are right. Before I've definitely upgraded to the latest conductr-cli but somehow I still used the old version during my first test.

Anyways, I'll revert my changes because your solution with the tab completion for the features is a better user experience.

**Pull request merged**
