### PR TITLE
Bumps conductr-lib to avoid metricsProvider override.

### LINKED ISSUE #270: Bump the version of conductr-lib
In order to complete the fix of https://github.com/lagom/lagom/issues/813 it will be necessary to [bump the version](https://github.com/typesafehub/sbt-conductr/blob/1691a79c340f92a1774d940fe94841213a406345/src/main/scala/com/lightbend/conductr/sbt/package.scala#L79-L79) of `conductr-lib` in `sbt-conductr`.

This is a multistep process involving conductr-lib and sbt-conductr repos (at least). To keep track of the evolution of this fix we have lagom/lagom#813 with a checklist in the description.

### PR DESCRIPTION
**Pull request by ignasi35**
Fixes #270

### CODE REVIEW

**Comment by longshorej** [comment]
jenkins

**Comment by ignasi35** [comment]
```
java.lang.RuntimeException: Failed tests:
	public / conduct-end-to-end
```
in travis. relaunching...

**Comment by ignasi35** [comment]
relaunching travis... is it a side effect of this PR or the build is flaky in travis ?

**Comment by ignasi35** [comment]
With #274 merged we can remove some of the changes here... rebasing.

**Comment by ignasi35** [comment]
This PR needs a new release of `conductr-lib` that includes https://github.com/typesafehub/conductr-lib/pull/153

**Comment by markusjura** [comment]
@ignasi35 But this would mean that this should bump the version up to 1.9.4, right?!

**Comment by markusjura** [comment]
@ignasi35 conductr-lib 1.9.4 libraries have been released. Can you upgrade the version in this PR accordingly?

**Pull request merged**
